apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: whatsthecharge-com-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whatsthecharge.com
      app.kubernetes.io/part-of: whatsthecharge.com
