name: "Build & Deploy"

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: whatsthecharge_test
          POSTGRES_PASSWORD: hunter2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:hunter2@localhost:5432/whatsthecharge_test

    steps:
      - uses: actions/checkout@v2

      - name: Read Ruby version
        run: echo ::set-output name=version::$(cat .tool-versions | grep ruby | cut -d ' ' -f 2)
        id: ruby-version

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ steps.ruby-version.outputs.version }}'

      - name: Read Node.js version
        run: echo ::set-output name=version::$(cat .tool-versions | grep nodejs | cut -d ' ' -f 2)
        id: node-version

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node-version.outputs.version }}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Run bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - run: bundle exec rails assets:precompile

      - run: bundle exec rails db:setup

      - run: bundle exec rails test

  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Create GitHub deployment
        id: deployment
        uses: actions/github-script@v3
        with:
          script: |
            const deployment = await github.repos.createDeployment({
              ...context.repo,
              ref: '${{ github.sha }}',
              environment: 'production',
              required_contexts: [],
              mediaType: { previews: ['flash', 'ant-man'] }
            })

            return deployment.data.id;

      - name: Create GitHub deployment in progress status
        uses: actions/github-script@v3
        with:
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'in_progress',
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })

      - name: Install pack
        run: curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.14.1/pack-v0.14.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack

      - name: Run docker login
        run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:latest

      - name: Run pack build
        run: |
          pack build --builder heroku/buildpacks --buildpack heroku/ruby \
            docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:${{ github.sha }}

      - name: Run docker tag
        run: |
          docker tag \
          docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:${{ github.sha }} \
          docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:latest

      - name: Run docker push
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:${{ github.sha }}
          docker push docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:latest

      - name: Run install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save k8s-lon1

      - name: Generate kustomize yaml files
        run: |
          cat >> k8s/kustomization.yaml <<EOF
          patchesStrategicMerge:
            - deployment-${{ github.sha }}.yaml
          EOF

          cat > k8s/deployment-${{ github.sha }}.yaml <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: whatsthecharge.com
            annotations:
              kubernetes.io/change-cause: "updated to revision https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          spec:
            template:
              spec:
                containers:
                  - name: web
                    image: docker.pkg.github.com/${{ github.repository }}/whatsthecharge.com:${{ github.sha }}
                    env:
                      - name: RAILS_APP_VERSION
                        value: ${{ github.sha }}
          EOF

      - run: kubectl apply -k k8s/

      - run: kubectl rollout status deployment/whatsthecharge.com --timeout=5m

      - name: Run rails db:migrate
        run: |
          sleep 30
          kubectl exec deployment/whatsthecharge.com -- /cnb/lifecycle/launcher bundle exec rails db:migrate

      - name: Create GitHub deployment success status
        uses: actions/github-script@v3
        if: success()
        with:
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'success',
              environment_url: 'https://whatsthecharge.com',
              auto_inactive: true,
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })

      - name: Create GitHub deployment failure status
        uses: actions/github-script@v3
        if: cancelled() || failure()
        with:
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'failure',
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })
